### ISSUE TITLE
Modify license?

### ISSUE THREAD

**Issue by JaneJeon** [JaneJeon/objection-authorize#151]
LGPL should be stronger, and given that at least one company is using a hard fork internally without contributing back, it sounds like a good appraoch

See: https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)

**Comment by jeremy-w** [comment]
this seems to rule out using objection-authorize in closed-source but publicly-distributed applications compiled together using something like webpack, as i read the LGPL 3:

- webpack produces a Combined Work
- to be able to swizzle out the Linked Version for my own custom version of the library, i probably need to be able to rerun the build, so i need the source.

MPL 2 (roughly, "file-level copyleft") seems to avoid the linking issues that LGPL raises, while still requiring contributing back changes for distributed software.

IIUC the LGPL still doesn't stop internal use of a hard fork, since it doesn't count as distribution, so doesn't trigger any of the related requirements. See for example the [GNU FAQ on releasing modified versions of GPL'd software](https://www.gnu.org/licenses/gpl-faq.en.html#GPLRequireSourcePostedPublic):

> You are free to make modifications and use them privately, without ever releasing them. This applies to organizations (including companies), too; **an organization can make a modified version and use it internally without ever releasing it outside the organization.** (emphasis added)

**Comment by JaneJeon** [comment]
@jeremy-w first off, LGPL doesn’t make it “unavailable” to private enterprises. You yourself pointed out - nothing stops them from just hard forking it internally and just never releasing it (though most companies basically consider GPL - not LGPL - essentially “off limits”).

As for your concerns about something like webpack producing a “combined work” and the *whole* application potentially falling under LGPL, first of all, if you’re keeping it internal, it’s all fine, and second of all, LGPL specifically makes a distinction between “static” and “dynamic” linking. Obviously, there *is* no “static” linking in javascript land - everything is dynamic, *technically*.

But in the context of this library (and the other `objection-*` libraries that I also release under LGPL), the scope of “statically linked” derivative work is pretty clear - stuff that is “linked” to specifically modify this library. This gets around the MPL loophole of someone just writing extra files (not touching the original library) that *modify* the behaviour of the original library without actually TOUCHING the files themselves.

So I hope I quelled your fears and misunderstandings about LGPL. Really, you can’t “force” private companies to contribute back; but should they contribute back, I prefer that they at least try to contribute back to the original library, instead of splitting an already small community (there’s probably maybe *dozens* of people who actually use Objection.js in production).
