### ISSUE TITLE
Condition in allow function always return false

### ISSUE THREAD

**Issue by BadPistol97** [JaneJeon/objection-authorize#160]
ACL:

```
const {defineAbility} = require('@casl/ability');

function acl(user, resource, action, body, opts, relation){
    

    console.log(user,resource,action,body,relation);

    return defineAbility((allow,forbid)=>{

        allow('read','UserProfile'); // works without condition

        allow('update','UserProfile',{user_id:user.id});      // error caught: ForbiddenError: Forbidden

    });
}

module.exports = acl;
```

User Model: 
```
const {Model} = require('objection');
const Password = require('objection-password')();

class User extends Password(Model){

    static get tableName(){
        return 'user';
    }

    static get idColumn(){
        return 'id';
    }

    static get jsonSchema(){
        return {
            type:'object',
            required:['username','email','password',],
            properties:{
                email:{type:'string'},
                username:{type:'string',minLength: 1, maxLength: 255},
                password:{type:'string',minLength: 1, maxLength: 255},
                role:{type:'string'}
            }
        }
    }


    static get relationMappings(){
        
        const UserProfile = require('./UserProfile');
        const UserAddress = require('./UserAddress');

        return{

            userProfile:{
                relation:Model.HasOneRelation,
                modelClass:UserProfile,
                join:{
                    from:'user.id',
                    to:'user_profile.user_id'
                }
            },

            userAddress:{
                relation:Model.HasManyRelation,
                modelClass:UserAddress,
                join:{
                    from:'user.id',
                    to:'user_address.user_id'
                }
            }

        }
    }
}

module.exports = User;
```

User Profile model:
```
const BaseModel = require('./BaseModel');

class UserProfile extends BaseModel{ 


    static get idColumn(){
        return 'id';
    }

    fullName(){
        return this.first_name+ " " +this.last_name;
    }

    static get jsonSchema(){
        return {
            type:'object',
            required:['user_id','birthday','phone_number'],
            properties:{
                user_id:{type:'integer'},
                birthday:{type:'string',format:'date-time'},
                phone_number:{type:'string',minLength: 1, maxLength: 255},
            }
        }
    }

    static get relationMappings(){

        const User = require('./User');

        return {
            user:{
                relation:BaseModel.BelongsToOneRelation,
                modelClass:User,
                join:{
                    from:'user_profile.user_id',
                    to:'user.id'
                }
            }
        }
    }


}

module.exports = UserProfile;
```

Update user profile: 
```
 await UserProfile.query().findById(1).patch( {
                                                    birthday:new Date().toISOString(),
                                                    first_name:'newName' 
                                                    }).authorize(req.user).then(result=>res.send(`result ${result}`)).catch(error=>res.send(`error ${error}`));
```
User Profile Table: 
![image](https://user-images.githubusercontent.com/42179618/116208543-9ce0fc00-a773-11eb-808c-aa308ae48fb7.png)

User Table: 
![image](https://user-images.githubusercontent.com/42179618/116208654-b71ada00-a773-11eb-9c55-09326ae98b77.png)

Console.log user parameter in acl function:
```
{
  role: 'admin',
  id: 1,
  username: 'user1',
  email: 'email1',
  password: 'password1',
  email_verified_at: 2021-04-26T18:09:53.000Z,
  created_at: 2021-04-26T18:09:53.000Z,
  updated_at: 2021-04-26T18:09:53.000Z
} 
```

**Comment by JaneJeon** [comment]
`allow('update','UserProfile',{user_id:user.id})`

^ you need to read the documentation about `fetchResourceContextFromDB` (in general, I recommend that you read through *every* method that is exposed by this library).

To explain, the above CASL query checks whether the user profile’s `user_id` is the same as `req.user.id`. However, the library has NO way of knowing what the user profile actually IS, until you query it and load it first. One way you could do it is by loading a `UserProfile` instance and running `.$query()` on it, or more simply, read the `fetchResourceContextFromDB` in the documentation.

Please read the documentation fully before making an issue :)

https://github.com/JaneJeon/objection-authorize#options

**Comment by TissuePowder** [comment]
@JaneJeon  I am sorry for digging up this closed issue, but I am confused about this same thing and would really appreciate if you could help me clear up a bit.

What I understand is that, `fetchResourceContextFromDB()` only returns something when an insert/update/patch query is done on the model; precisely returning the affected rows. So, if I chain it on a plain `read` query, like `User.query().authorize().fetchResourceContextFromDB()`, it won't return anything at all. And since no resource context was returned, condition on the line `allow('update','UserProfile',{user_id:user.id})` will not work.

But if I do `$query` on a model instance like the following:
```
let admin = await User.query().findOne({ role: 'admin' });
let x = await admin.$query().authorize(admin).fetchResourceContextFromDB();
```
it's still useless because now I get only the admin's row from the User table, not all rows where I can apply the filter condition.

So if I want to make the condition in `allow('update','UserProfile',{user_id:user.id})` work as intended, what should I do?

**Comment by JaneJeon** [comment]
Kind of, but not really. `fetchResourceContextFromDB` makes sure that if you're running policy X on object A, the object A gets loaded via the query (if it hasn't already, as you pointed out with the `$query`). It's not necessarily about read vs. write.

> So if I want to make the condition in allow('update','UserProfile',{user_id:user.id}) work as intended, what should I do?

For this, I will have to ask you to read the answer above:

> One way you could do it is by loading a UserProfile instance and running .$query() on it, or more simply, read the fetchResourceContextFromDB in the documentation.

Think about what context you need to make that decision - you need to know the _id_ of the person to be updated, and the _id_ of the person updating.

So if you wanted to do it properly, it would look something like this:

```js
const userToUpdate = await User.query().findById(blah) // load the user context
await userToUpdate.$query().authorize(req.user).update(userDetails) // use that loaded context + pass in the user that is doing the update via `.authorize(user)`
```

Or, you could use `fetchResourceContextFromDB`:

```js
await User.query().authorize(req.user).findById(blah).update(userDetails).fetchResourceContextFromDB() // the user context for the user to be updated will be pulled in through `fetchResourceContextFromDB`
```

OR, since the condition only depends on the id, you could "cheat" and pass in objects with just the id, and not necessarily load the whole object (because again, you only need the id):

```js
await User.query().authorize(req.user, { id: blah }).findById(blah).update(userDetails) // remember, `.authorize(user[, resource])`
```

Please please **please**, read this section _very_ carefully: https://github.com/JaneJeon/objection-authorize#methods. I've had to answer this like 5 times already...

**Comment by TissuePowder** [comment]
Thank you for the explanation. I apologize for making you repeat the explanation for that many times, but I really did read the documentation before asking my question. I mean, I appreciate your project big time, of course I want to have the courtesy of reading the doc at least. But I am not much experienced with the internals of how ACL is working under the hood, so I was still confused even after reading the documentation.

The reason of my confusion was because.... I think I was trying to do something that I wasn't meant to do? I was trying to use your plugin for the follow scenario:

An endpoint, supposedly `/posts` is open to public and anyone (supposedly people with `anonymous` role) can make a GET request there to get the full list of posts. I was thinking if I can make a condition so that I can filter specific rows, like only fetching rows `.where('creator', 'richard')`, or something like this. I was doing the following.

```js
const { defineAbility } = require("@casl/ability");

const acl = (user, resource, action, body, opts, relation) => {
  return defineAbility((can, cannot) => {
    can('read', 'User', {creator: 'richard'});
  });
};

module.exports = acl;
```

```js
const Post = require('../models/post');

exports.getPosts = async (req, res, next) => {
    try {
        let posts = await Post.query().authorize().fetchResourceContextFromDB();
        res.status(200).json(posts);
    }
    catch (err) {
        next(err);
    }
}
```

I guess my problem was that I was trying to `filter` things which is fully different than what `authorization` here is meant to achieve? But anyhow if I am wrong, is filtering actually doable through the acl here?

**Comment by JaneJeon** [comment]
Right, this library doesn't have the ability to automatically "filter" results in _queries_.

However, what it _can_ do is to filter _query results_ according to someone's access. That is what `.authorizeRead()` is all about in the `methods` section: https://github.com/JaneJeon/objection-authorize#methods (so like I said, it's in the docs)

**Comment by TissuePowder** [comment]
Yeah I noticed the `.authorizeRead()` method, but I was thinking if this can be done with the {key : value} conditioning method too. But anyway, I got my answer. Thank you very much again.
