### ISSUE TITLE
Is it possible to retrieve and use permission defined in DB?

### ISSUE THREAD

**Issue by BadPistol97** [JaneJeon/objection-authorize#162]
If I were to allow permissions to be changed dynamically via DB tables, is it possible to do it one shot in `.authorize()` ?

I can think of querying making another query in the controller before the one with `.authorize()`. 

Could you give me an example if you have better solution?

**Comment by JaneJeon** [comment]
Hey, I have used the same pattern before (permissions depended on settings, settings could be changed by user).

Ideally, you would load all of the necessary (dynamic) context BEFORE you call .authorize() and pass it on to the query (the permissions HAVE to be synchronous, I made that rather clear in the documentation), rather than querying the context (which is async) WITHIN the permissions.

I should’ve clarified in the docs, but that is a HUGE anti-pattern. PLEASE do not make async calls to “fetch” context within the actual ACL/permission checking function, not only because it basically breaks objectionjs’s internal workings and cause unbound, undefined query execution time, but also because making database calls *breaks* isomorphism - a core goal and feature of this library.

For example, in my use case, let’s say I added async permission support and dynamically “fetch” the settings object *within* the permission function itself. If I do that, I can’t re-use the same authorization logic across frontend and backend, because the permission will have an inherently backend-coupled logic (e.g. `await Settings.query()`).

That’s why I strongly encourage decoupling the fetching of context and the actual execution of the authorization logic. And this pattern *is* proven to be isomorphic with my projects, so I encourage you to try it out “my way” and experience the glory of isomorphism for yourself.

So yes, you would need to make another query and fully await the results before you call .authorize()
